### PR TITLE
Prepare version 1.2.0

### PR DESCRIPTION
**Pull request by joaomhmpereira**
Update the version of cvc5 supported by the bindings to v1.2.0

### CODE REVIEW

**Comment by filipeom** [comment]
This fixes the `compare_pointer` warning I was getting with the version in opam, but now I also get: 

```
File "bin/dune", line 2, characters 7-11:
2 |  (name main)
           ^^^^
/usr/bin/ld: /home/filipe/.local/share/opam/ocaml-variants.5.2.0+options/lib/cvc5/libcvc5.a(cadical.cpp.o): in function `cvc5::internal::prop::CadicalSolver::getProofSketch()':
cadical.cpp:(.text+0x4de): undefined reference to `CaDiCaL::Solver::flush_proof_trace(bool)'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking (exit code 1)
```

When trying to compile smtml with this version

**Comment by joaomhmpereira** [comment]
This should fix it. @filipeom can you check it? (I can't reproduce the error)

**Comment by filipeom** [comment]
> This should fix it. @filipeom can you check it? (I can't reproduce the error)

In the `smtml` CI it seems to build fine, I'm only experiencing these issues locally

**Comment by filipeom** [comment]
Confirm, it seems to only happen on 5.2

**Pull request merged**
